name: Docker Build

on:
  push:
    branches:
      - dev
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate PHP syntax
        run: |
          find . -name "*.php" -exec php -l {} \;

      - name: Build Docker image
        run: docker build -t issue-tracker .